### PR TITLE
dependency logstash-core-plugin-api >= 1.60 <= 2.99

### PR DESCRIPTION
**Pull request by kjschnei001**
This is a copy of https://github.com/logstash-plugins/logstash-output-kafka/commit/d772a5422e64f727ef10a196ed226784673e5d68 for the `4.x` branch. This dependency is causing installation conflicts in our environments, so please merge unless there really is a dependency on `v2.0` of `logstash-core-plugin-api`

### CODE REVIEW

**Comment by kjschnei001** [comment]
I have now signed the CLA, but I'm not sure if the check will re-trigger

**Comment by karmi** [comment]
Hi @kjschnei001, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-output-kafka/pull/103.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by kjschnei001** [comment]
Thanks @karmi .  The commit email has been added to my profile

**Comment by talevy** [comment]
👍 @kjschnei001 good catch! and thanks for the complete PR with changelog and everything!

I'll merge this in and publish the new version shortly

**Pull request merged**
