### PR TITLE
added zstd as acceptable compression type

### PR DESCRIPTION
**Pull request by reschex**
Zstandard is supported by Kafka since version 2.1.0, which has been added recently in https://github.com/logstash-plugins/logstash-output-kafka/releases/tag/v7.3.0.

Making use of zstd was only prevented by logstash config validation.

I've also added a few missing "lz4"s into the documentation and comments.

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @reschex, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/logstash-plugins/logstash-output-kafka/pull/226.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by reschex** [comment]
as per #208 and https://github.com/logstash-plugins/logstash-output-kafka/issues/210#issuecomment-454567045 - exposing zstd only. compression level is an entirely new config setting and requires more work

**Comment by immon** [comment]
@jsvd any chances to get this merged?

**Comment by roaksoax** [comment]
Hi all! We are closing this PR because it has already been fixed in https://github.com/logstash-plugins/logstash-integration-kafka/pull/112 and available in the plugin version 10.10.0.

**Pull request closed without merging**
