### PR TITLE
Transform the instance var producer into a class var.

### PR DESCRIPTION
**Pull request by julien-girard**
Fix issue : https://github.com/elastic/logstash/issues/4754

### CODE REVIEW

**Comment by julien-girard** [comment]
The @@producer var needs to be reset between test to be sure that a new plugin object will not use the previously instantiated kafka producer. 
I have not found an elegant way to do it for now.

**Comment by jordansissel** [comment]
We shouldn't do this.

For users: A user could have multiple Kafka outputs configured, and this would cause the first-configured Kafka producer to be the only configured one.  The effect of this could be something from weird performance issues all the way to complete failures (for example, if two kafka outputs have different SSL 

For testing: global singleton-style things make it very hard to test things (because the first `register` call in a test suite will become the only producer settings possible). Even if we reset the value as you propose, this would prevent us from running tests concurrently within the same test run (something we don't do today, but could in the future).

**Comment by jordansissel** [comment]
I am open to further discussion, but for reasons detailed above, I believe this is the wrong approach to the concern described in elastic/logstash#4754

**Comment by jordansissel** [comment]
Despite closing this, I very much appreciate your efforts to make logstash more awesome!

**Comment by julien-girard** [comment]
You're absolutely right, i haven't been thinking about the multiple kafka outputs. I will come back to you with a better approach.

**Pull request closed without merging**
