### PR TITLE
Create a new class in charge of the kafka producer creation.

### PR DESCRIPTION
**Pull request by julien-girard**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

This way, worker using the same configuration will use the
same kafka producer object.

This will improve the performances as explained here :
https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/producer/KafkaProducer

Fix issue : https://github.com/elastic/logstash/issues/4754

### CODE REVIEW

**Comment by talevy** [comment]
Hi @julien-girard! We appreciate your contribution!

After thinking this problem through a bit, I realize that our new pipeline handles this use-case gracefully. When declaring the output plugin to be `threadsafe`, the pipeline will reuse the same instance across workers. This way, you do not have to manage the same `@producer` instance across copies of the plugin.

To make this actually be executed this way, the changes is #78 need to be completed.

I believe this should solve your problem in a way that is more in line with the new pipeline semantics.

further explanation of the semantics can be found here: https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html where it speaks about the `declare_threadsafe` functionality.

what do you think?

**Comment by julien-girard** [comment]
It would be much more simpler than my solution. I will test it monday and give you a feed back.
Thanks.

**Comment by julien-girard** [comment]
Hi,

I have been testing the 2.3.4 version of logstash. I still experience the same issue, logstash create a kafka client for each worker and each kafka client create a thread.

To resume, if workers parameter is set to 1, everything work as expected but if I
 set workers parameter to 20 for exemple, I observe in jvisualvm 20 kafka-producer-network-thread threads.

screenshot from 2016-07-18 13-23-15

**Comment by talevy** [comment]
@julien-girard didn't get a chance to update it, but will get to it soon and update you. thanks for trying it out!

**Comment by talevy** [comment]
@julien-girard, #79 is the right way to leverage pipeline workers I believe. Let me know what you think!

**Comment by julien-girard** [comment]
Looks nice. I was thinking this plugin was already threadsafe. Well, i close this pull request which make no sense now.

Thanks.

**Pull request closed without merging**
