### PR TITLE
Retry send only for retriable exceptions

### LINKED ISSUE #172: Plugin to provide better error logging
Logstash v5.6.4
Kafka version : 0.10.0.1

Ingestion coming from a variety of log sources like beats and syslog and sending to Kafka.

The INFO level log lines do not give a lot of detail into what is causing the failure.
```
2018-01-09T09:31:46,097][INFO ][logstash.outputs.kafka ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.01} 
[2018-01-09T09:31:46,113][INFO ][logstash.outputs.kafka ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.01} 
[2018-01-09T09:31:46,129][INFO ][logstash.outputs.kafka ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.01}
```

Once DEBUG logging is enabled then we see the particular:
```
[2018-01-09T15:58:26,995][DEBUG][logstash.outputs.kafka  ] KafkaProducer.send() failed: org.apache.kafka.common.errors.RecordTooLargeException: The message is
10486822 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration. {:exception=>java.util
.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordTooLargeException: The message is 10486822 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.}
[2018-01-09T15:58:26,997][INFO ][logstash.outputs.kafka  ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.01
```

Is it possible to have better error logging with this plugin?

### LINKED ISSUE #178: Better handle org.apache.kafka.common.errors.RecordTooLargeException
Currently we retry indefinitely when encountering this error. We should:

1. Always log these errors at 'warn'
2. Consider drop/log, or DLQ as paths for this permanent failure.

### LINKED ISSUE #190: Unable to recover from RecordTooLargeException
When RecordTooLargeException is returned by the kafka server, it is an unhandled exception and logstash retries forever, driving up the CPU on the host.

This is the Debug message in the log
KafkaProducer.send() failed: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.

Can RecordTooLargeException be caught explicitly and handled the same as Timeout or Interrupt exceptions?

https://github.com/logstash-plugins/logstash-output-kafka/blob/146f3f5dce786b8a8b385ec86b27b1b1fb1ab9ad/lib/logstash/outputs/kafka.rb#L259

```
      futures = batch.collect do |record| 
        begin
          # send() can throw an exception even before the future is created.
          @producer.send(record)
        rescue org.apache.kafka.common.errors.TimeoutException => e
          failures << record
          nil
        rescue org.apache.kafka.common.errors.InterruptException => e
          failures << record
          nil
        rescue org.apache.kafka.common.errors.SerializationException => e
          # TODO(sissel): Retrying will fail because the data itself has a problem serializing.
          # TODO(sissel): Let's add DLQ here.
          failures << record
          nil
        end
      end.compact
```

### LINKED ISSUE #193: Separate behaviour for retriable and non-retriable exceptions
Currently this plugin will retry producing events for any exception, even those that are not retriable (e.g. a `SerializationException`). By default there is [no limit on the number of retries](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html#plugins-outputs-kafka-retries) which causes these kind of failures to infinitely hang the entire Logstash pipeline.

Fortunately, the Kafka client library already provides a [`RetriableException` base class](https://kafka.apache.org/0110/javadoc/org/apache/kafka/common/errors/RetriableException.html) for exceptions that are retriable (such as a [`TimeoutException`](https://kafka.apache.org/0110/javadoc/org/apache/kafka/common/errors/RetriableException.html)). It makes a lot of sense to implement retry logic only for exceptions that inherit `RetriableException` and drop or send-to-DLQ events that are not.

### PR DESCRIPTION
**Pull request by praseodym**
Fixes #193 
Fixes #190
Fixes #178 
Fixes #172

## Current situation

Infinite retry for permanent failure (`RecordTooLargeException`):
```
[2018-06-13T22:01:44,766][INFO ][logstash.outputs.kafka   ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.1}
[2018-06-13T22:01:44,868][WARN ][logstash.outputs.kafka   ] KafkaProducer.send() failed: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept. {:exception=>java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.}
[2018-06-13T22:01:44,869][INFO ][logstash.outputs.kafka   ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.1}
[2018-06-13T22:01:44,971][WARN ][logstash.outputs.kafka   ] KafkaProducer.send() failed: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept. {:exception=>java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.}
[2018-06-13T22:01:44,971][INFO ][logstash.outputs.kafka   ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.1}
[2018-06-13T22:01:45,073][WARN ][logstash.outputs.kafka   ] KafkaProducer.send() failed: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept. {:exception=>java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.}
```

## New situation

`RecordTooLargeException` gets dropped and logged:
```
[2018-06-13T22:34:00,398][WARN ][logstash.outputs.kafka   ] KafkaProducer.send() future failed, dropping record {:exception=>org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept., :event=>"{\"message\":\"something that is larger than max.message.bytes\"@timestamp\":\"2018-06-13T20:34:00.116Z\",\"@version\":\"1\",\"host\":\"hostname\",\"sequence\":0}"}
```
Transient failures, like a broker restart, are still handled just fine (single server cluster in this case):
```
[2018-06-13T22:40:31,204][WARN ][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Connection to node 0 could not be established. Broker may not be available.
[2018-06-13T22:40:31,214][WARN ][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Connection to node 0 could not be established. Broker may not be available.
[2018-06-13T22:40:31,392][WARN ][org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] Error while fetching metadata with correlation id 7 : {test=LEADER_NOT_AVAILABLE}
[2018-06-13T22:40:31,398][WARN ][org.apache.kafka.clients.producer.internals.Sender] [Producer clientId=producer-1] Received unknown topic or partition error in produce request on partition test-0. The topic/partition may not exist or the user may not have Describe access to it
[2018-06-13T22:40:31,402][INFO ][logstash.outputs.kafka   ] KafkaProducer.send() future failed, will retry {:exception=>org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.}
[2018-06-13T22:40:31,402][INFO ][logstash.outputs.kafka   ] KafkaProducer.send() future failed, will retry {:exception=>org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.}
[2018-06-13T22:40:31,402][INFO ][logstash.outputs.kafka   ] KafkaProducer.send() future failed, will retry {:exception=>org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.}
[2018-06-13T22:40:31,402][INFO ][logstash.outputs.kafka   ] KafkaProducer.send() future failed, will retry {:exception=>org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.}
[2018-06-13T22:40:31,403][INFO ][logstash.outputs.kafka   ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.1}
[2018-06-13T22:40:31,403][INFO ][logstash.outputs.kafka   ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.1}
[2018-06-13T22:40:31,403][INFO ][logstash.outputs.kafka   ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.1}
[2018-06-13T22:40:31,403][INFO ][logstash.outputs.kafka   ] Sending batch to Kafka failed. Will retry after a delay. {:batch_size=>1, :failures=>1, :sleep=>0.1}
```

### CODE REVIEW

**Comment by praseodym** [comment]
CI failure looks like a flake

**Review by robbavey — COMMENTED** [review]
@praseodym Thanks for the contribution.

On the whole, I like the change - there is no reason to continue to retry sending messages that will never successfully be sent, but I do have some concerns that we are changing the default behavior to drop events over what could be a misconfiguration/miscalculation of `max_request_size`, for example, but without DLQ support, we don't really have a great story here.

cc @jsvd for his opinion

**Comment by praseodym** [comment]
Agreed, having a DLQ would be the best solution for this. As the (in my opinion) second best option, I chose to log the entire Logstash event (Kafka record value). This way, it is at least possible to debug what kind of messages are dropped.

**Comment by praseodym** [comment]
ping @jsvd @robbavey, any obligations on getting this merged?

**Comment by praseodym** [comment]
ping @robbavey @jsvd; any comments on this?

**Comment by xraystyle** [comment]
Hey everyone, was there ever any movement on this? Seems I've hit this issue in production and it's a bit of a show-stopping problem if enough of these messages build up and are constantly retrying.

**Comment by praseodym** [comment]
This PR still works on the `master` branch. If there’s anything holding back a merge of this PR, please let me know.

**Comment by praseodym** [comment]
@robbavey @jsvd can we get this merged? It has been over half a year and I'm not sure what we're waiting for.

**Comment by praseodym** [comment]
After rebasing I noticed that the CI failure was caused by an actual problem in the spec (vs. actual behaviour). This is fixed in a new commit.

I also noticed that `retrying_send` would sometimes retry the wrong message because it uses incorrect array indexing. This problem is present in current releases as well. It is fixed in another new commit in this PR.

**Comment by robbavey** [comment]
@jsvd Are you good to go with this after the most recent push?

**Comment by praseodym** [comment]
Apparently I missed two specs, now fixed.

**Comment by Pectojin** [comment]
Is there any reason this isn't getting merged?

I don't really know what to do with a plugin that will DOS itself to death... It seems pretty critical.

**Comment by praseodym** [comment]
I'm not sure; maybe @robbavey @jsvd have any comments on this?

**Comment by praseodym** [comment]
Closing in favour of https://github.com/logstash-plugins/logstash-integration-kafka/pull/29.

**Pull request closed without merging**
