### PR TITLE
Update output to latest jruby-kafka.

### PR DESCRIPTION
**Pull request by joekiller**
This brings in the latest jruby-kafka as well as partition key selection via the key_serializer_class
necessary jars are now bundled in jruby-kafka gem

### CODE REVIEW

**Comment by talevy** [comment]
sweet! its nice to have more control over partitioning. I am still reviewing this, while doing so. I got this
warning for the `partition.key.format` config

```
~/Code/es/talevy-logstash-output-kafka (pr/12)$ bundle exec rspec
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :broken=>true, :export_cypher=>true, :integration=>true, :windows=>true}
....WARNING: Unknown configuration key: partition.key.format
.

Finished in 0.479 seconds
5 examples, 0 failures
```

**Comment by joekiller** [comment]
Oops I'll check this out

**Comment by joekiller** [comment]
There we go.

**Comment by talevy** [comment]
LGTM

**Comment by talevy** [comment]
@joekiller bumped version and published to rubygems: https://rubygems.org/gems/logstash-output-kafka/versions/0.1.7

thanks!

p.s. about to do the same with logstash-input-kafka

**Pull request closed without merging**
