### PR TITLE
fix logger setup for 5.0 and bump version to 4.0.2

### PR DESCRIPTION
**Pull request by talevy**

### CODE REVIEW

**Comment by suyograo** [comment]
You missed the changelog entry :)

LGTM otherwise, but lets wait for travis

**Comment by talevy** [comment]
comparable to the change for `5.0` here: https://github.com/logstash-plugins/logstash-output-kafka/commit/49f80fe699069851c8c7e0e080db0929dd64cf19#diff-c6a637e53249d2c5a0ee842b0bc19e82L120

**Comment by talevy** [comment]
@suyograo updated the changelog, please review!

**Comment by suyograo** [comment]
LGTM

**Pull request merged**
