### PR TITLE
Revert to jruby-kafka 1.5.0 dependency

### PR DESCRIPTION
**Pull request by suyograo**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by joekiller** [comment]
What happened?

**Comment by suyograo** [comment]
@joekiller we are seeing a couple of issues when building Logstash artifacts with jruby-kafka 1.6.0. 
1. Its super weird, but on 2.3 branch (which we are trying to release tomorrow) we are seeing maven issues which ultimately result in manticore issues (https://github.com/elastic/logstash/issues/5188)

```
Successfully installed bundler-1.9.10
Invoking bundler install...
Error Bundler::InstallError, retrying 1/10
An error occurred while installing manticore (0.5.5), and Bundler cannot continue.
Make sure that `gem install manticore -v '0.5.5'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
```

Another error:

```
Installing logstash-input-http 2.2.2
  jar dependencies for manticore-0.5.5-java.gemspec . . .
Installing gem 'ruby-maven' . . .

RuntimeError: there was an error installing 'ruby-maven (~> 3.3.3)' . please install it manually: #<Gem::DocumentError: RDoc is not installed: no such file to load -- rdoc/rdoc>
```

See http://build-eu-00.elastic.co/job/logstash_create_deb_artifact_23/jdk=JDK7,label=metal-pool/30/console

Now, by process of elimination we zeroed in on this update -- when we go back to jruby-kafka 1.5.0, everything is fine! We reviewed the changes from 1.5 and 1.6 and doesn't seem to be much

**Comment by talevy** [comment]
LGTM

**Comment by suyograo** [comment]
@joekiller can you tell us why you are doing this? https://github.com/joekiller/jruby-kafka/blob/v1.6/jruby-kafka.gemspec#L21

**Pull request closed without merging**
