### PR TITLE
Point users+contributors to integration source

### PR DESCRIPTION
**Pull request by karenzone**
The forward-moving source of this plugin is now a part of the Kafka Integration. This PR is intended to point users and contributors to the new integration repo.

### CODE REVIEW

**Comment by andsel** [comment]
LGTM

**Comment by yaauie** [comment]
These changes look good.

There is a failing spec on Logstash 5.x that I think should be resolved before we push a new artifact. I'll take a look at that shortly and help get the build to green.

**Comment by yaauie** [comment]
The `5.6` build ended up fixing itself after I retried the job a couple times.

IIRC I hit similar issues (`ConcurrencyError: interrupted waiting for mutex: null`) a long while ago on this project or one like it and chased it down to rspec's mock verification (expecting a message to be sent to a partial mock) not being threadsafe.

However, the matrix for this project wasn't updated to point to Logstash `7.x` when `7.x` was cut from `master`, so I have also opened #231 to resolve that and other testing issues.

**Comment by yaauie** [comment]
Also: we can merge this as-is, since no new artifact needs to be pushed (doc changes are asciidoc source comment only, won't affect the doc build).

**Pull request merged**
